import test from 'node:test';
import assert from 'node:assert/strict';
import { runCorrection } from '../src/battelle-correction.js';
import { loadAndNormalizeItems, loadJson } from '../src/battelle-data.js';
import { loadScaleModel } from '../src/battelle-scales.js';
import { loadNormativeData } from '../src/battelle-conversions.js';
import { scoreAssessment } from '../src/battelle-scoring.js';
import { ASSESSMENTS_KEY, LEGACY_V2_KEY, MIGRATION_KEY, WORKFLOW_STATUS, COLLECTION_ERROR, createAssessmentRecord, saveAssessment, listAssessments, getAssessment, deleteAssessment, migrateLegacyAssessment, filterAssessments, sanitizeRecord, readCollectionStatus } from '../src/battelle-assessment-repository.js';
import { VIEW_MODE, applyCorrectionResult, applyNonScoringChange, applyScoringChange, enterEditMode, reopenBlocked, reopenCorrected } from '../src/battelle-assessment-workflow.js';
import { isStrictIsoDate } from '../src/battelle-state.js';
class Mem{constructor(fail=false){this.m=new Map;this.fail=fail}getItem(k){return this.m.get(k)??null}setItem(k,v){if(this.fail)throw new Error('quota');this.m.set(k,v)}removeItem(k){this.m.delete(k)}}
const clock=(...dates)=>{let i=0;return()=>dates[Math.min(i++,dates.length-1)]};

test('updatedAt nuevo en cada guardado, createdAt estable, reordena y guarda respuestas/observaciones', async()=>{const s=new Mem; const now=clock('2026-01-01T00:00:00.000Z','2026-01-02T00:00:00.000Z','2026-01-03T00:00:00.000Z','2026-01-04T00:00:00.000Z'); let a=createAssessmentRecord({id:'bat-a1',name:'Ana',createdAt:'2025-01-01T00:00:00.000Z',updatedAt:'2025-01-01T00:00:00.000Z'}); let b=createAssessmentRecord({id:'bat-b2',name:'Beto',updatedAt:'2025-02-01T00:00:00.000Z'}); a=await saveAssessment(a,s,{now}); b=await saveAssessment(b,s,{now}); a.observedResponses.A1=2; a=await saveAssessment(a,s,{now}); a.observations.A1='nota'; a=await saveAssessment(a,s,{now}); assert.equal(a.createdAt,'2025-01-01T00:00:00.000Z'); assert.equal(a.updatedAt,'2026-01-04T00:00:00.000Z'); assert.equal((await listAssessments(s))[0].id,'bat-a1'); assert.equal((await getAssessment('bat-a1',s)).observations.A1,'nota');});
test('cambiar nombre actualiza updatedAt y lastSavedAt recibe el nuevo valor por contrato', async()=>{const s=new Mem; let lastSavedAt=null; let a=await saveAssessment(createAssessmentRecord({id:'bat-a1'}),s,{now:()=> '2026-01-01T00:00:00.000Z'}); a.name='Nuevo'; a=await saveAssessment(a,s,{now:()=> '2026-01-02T00:00:00.000Z'}); lastSavedAt=a.updatedAt; assert.equal(lastSavedAt,'2026-01-02T00:00:00.000Z');});
test('eliminar únicamente una, abrir por ID y búsqueda/filtros', async()=>{const s=new Mem; await saveAssessment(createAssessmentRecord({id:'bat-a1',name:'Ana'}),s); await saveAssessment(createAssessmentRecord({id:'bat-b2',name:'Beto',workflowStatus:WORKFLOW_STATUS.CORRECTED}),s); await saveAssessment(createAssessmentRecord({id:'bat-c3',name:'Cara',workflowStatus:WORKFLOW_STATUS.STALE}),s); assert.equal((await getAssessment('bat-b2',s)).name,'Beto'); assert.equal(filterAssessments(await listAssessments(s),{query:'ana'}).length,1); assert.equal(filterAssessments(await listAssessments(s),{filter:'corrected'}).length,1); assert.equal(filterAssessments(await listAssessments(s),{filter:'attention'}).length,1); await deleteAssessment('bat-a1',s); assert.equal(await getAssessment('bat-a1',s),null); assert.equal((await listAssessments(s)).length,2);});
test('migración única desde V2, corrupta y borrador antiguo no se duplica', async()=>{const s=new Mem; s.setItem(LEGACY_V2_KEY,JSON.stringify({assessment:{id:'bat-old',schemaVersion:2,name:'Viejo',birthDate:'2020-01-01',assessmentDate:'2026-01-01',ageMonths:72,manualAgeOverride:false,observedResponses:{A1:1},observations:{},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}})); assert.equal((await migrateLegacyAssessment(s)).status,'migrated'); assert.equal((await migrateLegacyAssessment(s)).status,'skipped'); assert.equal((await listAssessments(s)).length,1); const c=new Mem; c.setItem(LEGACY_V2_KEY,'{bad'); assert.equal((await migrateLegacyAssessment(c)).status,'corrupt'); assert.equal(c.getItem(MIGRATION_KEY),null);});
test('validación estricta, claves peligrosas, fecha imposible y año bisiesto',()=>{const r=createAssessmentRecord({id:'bat-ok'}); assert.ok(sanitizeRecord(r)); assert.equal(sanitizeRecord({...r,observedResponses:{constructor:1}}),null); assert.equal(sanitizeRecord({...r,observedResponses:{A1:3}}),null); for(const d of ['2026-02-29','2026-02-30','2026-02-31','2026-00-01','2026-13-01','2026-01-00']) assert.equal(isStrictIsoDate(d,false),false); assert.equal(isStrictIsoDate('2024-02-29',false),true);});
test('correctionMetadata solo con result.ok y bloqueada no contiene fingerprint válido nuevo',()=>{const base=createAssessmentRecord({id:'bat-ok',correctionMetadata:{fingerprint:'old'}}); const ok=applyCorrectionResult({assessment:base,result:{ok:true,status:'corregida',correctedAt:'t',fingerprint:'fp',normativeVersion:'norm'}}); assert.equal(ok.workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(ok.correctionMetadata.fingerprint,'fp'); const blocked=applyCorrectionResult({assessment:ok,result:{ok:false,status:'correccion_bloqueada',errors:[{}],pendingReport:{total:3}}}); assert.equal(blocked.workflowStatus,WORKFLOW_STATUS.BLOCKED); assert.equal(blocked.correctionMetadata.fingerprint,undefined); assert.equal(blocked.correctionMetadata.pendingCount,3);});
test('editar corregida sin cambios conserva estado; nombre y observación no invalidan; puntuación, fecha y edad invalidan',()=>{const corrected=createAssessmentRecord({id:'bat-ok',workflowStatus:WORKFLOW_STATUS.CORRECTED,correctionMetadata:{fingerprint:'fp'},observedResponses:{A1:1},observations:{A1:'a'}}); assert.equal(enterEditMode(corrected).assessment.workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(applyNonScoringChange(corrected,{name:'Otro'}).workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(applyNonScoringChange(corrected,{observations:{A1:'b'}}).workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(applyScoringChange(corrected,{observedResponses:{A1:2}}).workflowStatus,WORKFLOW_STATUS.STALE); assert.equal(applyScoringChange(corrected,{assessmentDate:'2024-02-01'}).workflowStatus,WORKFLOW_STATUS.STALE); assert.equal(applyScoringChange(corrected,{manualAgeOverride:true,ageMonths:50}).workflowStatus,WORKFLOW_STATUS.STALE);});
test('colección superior corrupta y registro individual corrupto', async()=>{const s=new Mem; s.setItem(ASSESSMENTS_KEY,'{bad'); assert.equal(readCollectionStatus(s).ok,false); await assert.rejects(saveAssessment(createAssessmentRecord({id:'bat-a1'}),s),e=>e.code===COLLECTION_ERROR.CORRUPT); const s2=new Mem; const valid=createAssessmentRecord({id:'bat-a1'}); s2.setItem(ASSESSMENTS_KEY,JSON.stringify({schemaVersion:3,revision:1,records:{'bat-a1':valid,'bat-bad':{...valid,id:'other',observedResponses:{A1:9}}}})); const rows=await listAssessments(s2); assert.equal(rows.length,1); assert.equal(rows.meta.omitted,1); await assert.rejects(saveAssessment(rows[0],s2),e=>e.code===COLLECTION_ERROR.OMITTED);});
test('conflicto de la misma evaluación y dos pestañas modificando evaluaciones diferentes', async()=>{const s=new Mem; let a=await saveAssessment(createAssessmentRecord({id:'bat-a1'}),s,{now:()=> '2026-01-01T00:00:00.000Z'}); let b=await saveAssessment(createAssessmentRecord({id:'bat-b2'}),s,{now:()=> '2026-01-01T00:00:00.000Z'}); const tabA=structuredClone(a), tabA2=structuredClone(a), tabB=structuredClone(b); tabA.name='uno'; await saveAssessment(tabA,s,{expectedRevision:tabA.revision,now:()=> '2026-01-02T00:00:00.000Z'}); tabA2.name='dos'; await assert.rejects(saveAssessment(tabA2,s,{expectedRevision:tabA2.revision}),e=>e.code===COLLECTION_ERROR.CONFLICT); tabB.name='otro'; await saveAssessment(tabB,s,{expectedRevision:tabB.revision,now:()=> '2026-01-03T00:00:00.000Z'}); assert.equal((await getAssessment('bat-b2',s)).name,'otro');});
test('error de cuota, no DOM ni funciones serializadas, nueva no elimina anterior y navegación espera guardado', async()=>{const fail=new Mem(true); await assert.rejects(saveAssessment(createAssessmentRecord({id:'bat-x1'}),fail),/quota/); const s=new Mem; const r=createAssessmentRecord({id:'bat-x1',extra:()=>{},node:{nodeType:1}}); await saveAssessment(r,s); assert.equal(s.getItem(ASSESSMENTS_KEY).includes('nodeType'),false); await saveAssessment(createAssessmentRecord({id:'bat-x2'}),s); assert.equal((await listAssessments(s)).length,2); let saved=false; await (async()=>{await saveAssessment(createAssessmentRecord({id:'bat-x3'}),s); saved=true;})(); assert.equal(saved,true);});
test('evento storage y detección entre pestañas comparan revisiones actuales',()=>{const openedRevision=1; const incoming={records:{'bat-a1':{revision:2,updatedAt:'u2'}}}; assert.equal(ASSESSMENTS_KEY,'battelleAssessmentsV3'); assert.notEqual(incoming.records['bat-a1'].revision,openedRevision);});
test('reapertura de bloqueada reconstruye pendientes y no muestra derivados',()=>{const assessment=createAssessmentRecord({id:'bat-blk',workflowStatus:WORKFLOW_STATUS.BLOCKED,observedResponses:{A1:1},correctionMetadata:{blockedAt:'t',pendingCount:1}}); const reopened=reopenBlocked({assessment,runCorrection:()=>({ok:false,status:'correccion_bloqueada',errors:[{message:'falta'}],pendingReport:{total:1,items:[{code:'A2'}]}})}); assert.equal(reopened.viewMode,VIEW_MODE.ADMINISTRATION); assert.equal(reopened.correction.pendingReport.total,1); assert.equal(reopened.score,null);});
test('reapertura completa de corregida, reconstrucción única, editar sin cambios y luego invalidar puntuación',()=>{let calls=0; const assessment=createAssessmentRecord({id:'bat-ok',workflowStatus:WORKFLOW_STATUS.CORRECTED,observedResponses:{A1:2},correctionMetadata:{fingerprint:'fp',normativeVersion:'norm',dataVersion:'items-v1',modelVersion:'model-v1'}}); const reopened=reopenCorrected({assessment,runCorrection:()=>{calls++; return {ok:true,status:'corregida',fingerprint:'fp',normativeVersion:'norm',scoring:{respuestas_efectivas:{}},results:{}};}}); assert.equal(calls,1); assert.equal(reopened.viewMode,VIEW_MODE.RESULTS); assert.ok(reopened.correction); const edit=enterEditMode(reopened.assessment); assert.equal(edit.assessment.workflowStatus,WORKFLOW_STATUS.CORRECTED); const stale=applyScoringChange(edit.assessment,{observedResponses:{A1:1}}); assert.equal(stale.workflowStatus,WORKFLOW_STATUS.STALE);});
test('integración real corregida: guardar, abrir, reconstruir una vez y conservar/invalida estado', async()=>{const items=await loadAndNormalizeItems(); const model=await loadScaleModel(); const normativeData=await loadNormativeData(loadJson); const observedResponses=Object.fromEntries(items.map(i=>[i.codigo_canonico,2])); let assessment=createAssessmentRecord({id:'bat-real',name:'Real',birthDate:'2020-01-01',assessmentDate:'2024-01-01',ageMonths:48,observedResponses}); const result=runCorrection({assessment,items,model,normativeData,scoreAssessment}); assert.equal(result.ok,true); assessment=applyCorrectionResult({assessment,result}); const s=new Mem; assessment=await saveAssessment(assessment,s,{now:()=> '2026-01-01T00:00:00.000Z'}); const opened=await getAssessment('bat-real',s); let calls=0; const reopened=reopenCorrected({assessment:opened,runCorrection:()=>{calls++; return runCorrection({assessment:opened,items,model,normativeData,scoreAssessment});}}); assert.equal(calls,1); assert.equal(reopened.evaluationStatus,'corregida'); assert.equal(reopened.correction.fingerprint,opened.correctionMetadata.fingerprint); assert.equal(reopened.viewMode,VIEW_MODE.RESULTS); assert.equal(enterEditMode(opened).assessment.workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(applyScoringChange(opened,{observedResponses:{...opened.observedResponses,[items[0].codigo_canonico]:1}}).workflowStatus,WORKFLOW_STATUS.STALE);});
import { createSaveCoordinator, guardBeforeLeaving } from '../src/battelle-save-coordinator.js';

test('Nueva Battelle y Volver no abandonan evaluación ante cuota, conflicto o corrupción', async()=>{const assessment={id:'bat-a1',name:'Cambios'}; let current=assessment; let created=0; const fail=async()=>({ok:false,error:new Error('quota')}); assert.equal(await guardBeforeLeaving({save:fail,onSuccess:()=>{created++; current={id:'bat-new'};}}),false); assert.equal(current.name,'Cambios'); assert.equal(created,0); const conflict=async()=>false; assert.equal(await guardBeforeLeaving({save:conflict,onSuccess:()=>{current=null;}}),false); assert.equal(current.name,'Cambios'); const corrupt=async()=>({ok:false,error:{code:COLLECTION_ERROR.CORRUPT}}); assert.equal(await guardBeforeLeaving({save:corrupt,onSuccess:()=>{current=null;}}),false); assert.equal(current.name,'Cambios');});

test('deleteAssessment protege registros omitidos y conserva localStorage byte a byte', async()=>{const s=new Mem; const valid=createAssessmentRecord({id:'bat-a1'}); const original=JSON.stringify({schemaVersion:3,revision:1,records:{'bat-a1':valid,'bat-bad':{...valid,id:'other',observedResponses:{A1:9}}}}); s.setItem(ASSESSMENTS_KEY,original); await assert.rejects(deleteAssessment('bat-a1',s,{expectedRevision:valid.revision}),e=>e.code===COLLECTION_ERROR.OMITTED); assert.equal(s.getItem(ASSESSMENTS_KEY),original);});

test('deleteAssessment valida expectedRevision y permite eliminar cuando coincide', async()=>{const s=new Mem; let rec=await saveAssessment(createAssessmentRecord({id:'bat-a1'}),s); const stale=rec.revision-1; await assert.rejects(deleteAssessment('bat-a1',s,{expectedRevision:stale}),e=>e.code===COLLECTION_ERROR.CONFLICT); assert.ok(await getAssessment('bat-a1',s)); await deleteAssessment('bat-a1',s,{expectedRevision:rec.revision}); assert.equal(await getAssessment('bat-a1',s),null);});

test('planificador flush cancela debounce y realiza un único guardado inmediato', async()=>{let calls=0; const snapshots=[]; const coord=createSaveCoordinator({saveSnapshot:async(s)=>{calls++; snapshots.push(s); return {...s,revision:calls};},applySaved:()=>{}}); coord.schedule({id:'bat-a1',name:'uno'},10_000); const result=await coord.flush({id:'bat-a1',name:'dos'}); const second=await coord.flush({id:'bat-a1',name:'dos'}); assert.equal(result.ok,true); assert.equal(second.skipped,true); assert.equal(calls,1); assert.equal(snapshots[0].name,'dos');});

test('cola de guardados serializa y una operación antigua no pisa cambios recientes', async()=>{const resolvers=[]; const applied=[]; const coord=createSaveCoordinator({saveSnapshot:(s)=>new Promise(resolve=>resolvers.push(()=>resolve({...s,saved:true}))),applySaved:(s)=>applied.push(s)}); const a=coord.enqueue({id:'bat-a1',name:'A'}); const b=coord.enqueue({id:'bat-a1',name:'B'}); await new Promise(resolve=>setImmediate(resolve)); resolvers[0](); await a; assert.equal(applied.length,0); await new Promise(resolve=>setImmediate(resolve)); resolvers[1](); await b; assert.equal(applied.at(-1).name,'B'); assert.equal(applied.length,1);});

test('migración idempotente ante fallo parcial al escribir marca', async()=>{class Partial extends Mem{setItem(k,v){ if(k===MIGRATION_KEY) throw new Error('mark failed'); super.setItem(k,v); }} const s=new Partial; s.setItem(LEGACY_V2_KEY,JSON.stringify({assessment:{id:'bat-old',schemaVersion:2,name:'Viejo',birthDate:'2020-01-01',assessmentDate:'2026-01-01',ageMonths:72,manualAgeOverride:false,observedResponses:{A1:1},observations:{},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}})); await assert.rejects(migrateLegacyAssessment(s),/mark failed/); assert.equal((await listAssessments(s)).length,1); const retry=await migrateLegacyAssessment(s); assert.equal(retry.status,'already_migrated'); assert.equal((await listAssessments(s)).length,1);});
