import test from 'node:test';
import assert from 'node:assert/strict';
import { ASSESSMENTS_KEY, LEGACY_V2_KEY, MIGRATION_KEY, WORKFLOW_STATUS, createAssessmentRecord, saveAssessment, listAssessments, getAssessment, deleteAssessment, clearAssessmentRepository, migrateLegacyAssessment, filterAssessments, sanitizeRecord } from '../src/battelle-assessment-repository.js';
class Mem{constructor(fail=false){this.m=new Map;this.fail=fail}getItem(k){return this.m.get(k)??null}setItem(k,v){if(this.fail)throw new Error('quota');this.m.set(k,v)}removeItem(k){this.m.delete(k)}}

test('crear varias, listar por updatedAt, abrir y no sobrescribir', async()=>{const s=new Mem; const a=createAssessmentRecord({id:'bat-a1',name:'Ana',updatedAt:'2026-01-01T00:00:00.000Z'}); const b=createAssessmentRecord({id:'bat-b2',name:'Beto',updatedAt:'2026-02-01T00:00:00.000Z',observedResponses:{A1:2},observations:{A1:'ok'}}); await saveAssessment(a,s); await saveAssessment(b,s); const list=await listAssessments(s); assert.equal(list[0].id,'bat-b2'); assert.equal((await getAssessment('bat-a1',s)).name,'Ana'); assert.equal((await getAssessment('bat-b2',s)).observedResponses.A1,2);});
test('eliminar únicamente una', async()=>{const s=new Mem; await saveAssessment(createAssessmentRecord({id:'bat-a1'}),s); await saveAssessment(createAssessmentRecord({id:'bat-b2'}),s); await deleteAssessment('bat-a1',s); assert.equal(await getAssessment('bat-a1',s),null); assert.ok(await getAssessment('bat-b2',s));});
test('búsqueda y filtros',()=>{const rows=[createAssessmentRecord({id:'bat-a1',name:'Ana'}),createAssessmentRecord({id:'bat-b2',name:'Beto',workflowStatus:WORKFLOW_STATUS.CORRECTED}),createAssessmentRecord({id:'bat-c3',name:'Cara',workflowStatus:WORKFLOW_STATUS.STALE})]; assert.equal(filterAssessments(rows,{query:'ana'}).length,1); assert.equal(filterAssessments(rows,{filter:'corrected'}).length,1); assert.equal(filterAssessments(rows,{filter:'attention'}).length,1);});
test('migración única desde V2 y borrador antiguo no se duplica', async()=>{const s=new Mem; s.setItem(LEGACY_V2_KEY,JSON.stringify({assessment:{id:'bat-old',schemaVersion:2,name:'Viejo',birthDate:'2020-01-01',assessmentDate:'2026-01-01',ageMonths:72,manualAgeOverride:false,observedResponses:{A1:1},observations:{},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}})); assert.equal((await migrateLegacyAssessment(s)).status,'migrated'); assert.equal((await migrateLegacyAssessment(s)).status,'skipped'); assert.equal((await listAssessments(s)).length,1);});
test('migración corrupta no bloquea ni marca hecha', async()=>{const s=new Mem; s.setItem(LEGACY_V2_KEY,'{bad'); assert.equal((await migrateLegacyAssessment(s)).status,'corrupt'); assert.equal(s.getItem(MIGRATION_KEY),null);});
test('validación estricta y claves peligrosas',()=>{const r=createAssessmentRecord({id:'bat-ok'}); assert.ok(sanitizeRecord(r)); assert.equal(sanitizeRecord({...r,observedResponses:{constructor:1}}),null); assert.equal(sanitizeRecord({...r,observedResponses:{A1:3}}),null); assert.equal(sanitizeRecord({...r,birthDate:'not-date'}),null);});
test('estado corregida, reapertura metadata y baremos diferentes marcan desactualizado por huella',()=>{const r=createAssessmentRecord({id:'bat-ok',workflowStatus:WORKFLOW_STATUS.CORRECTED,correctionMetadata:{fingerprint:'abc',normativeVersion:'n1'}}); assert.equal(r.workflowStatus,WORKFLOW_STATUS.CORRECTED); assert.equal(r.correctionMetadata.fingerprint,'abc');});
test('cambio puntuación fecha edad invalida; nombre y observación no invalidan (contrato de huella)', async()=>{const { createCorrectionFingerprint }=await import('../src/battelle-correction.js'); const r=createAssessmentRecord({id:'bat-ok',birthDate:'2020-01-01',assessmentDate:'2024-01-01',observedResponses:{A1:1},observations:{A1:'a'}}); const fp=createCorrectionFingerprint({assessment:r,normativeVersion:'n1'}); assert.notEqual(createCorrectionFingerprint({assessment:{...r,observedResponses:{A1:2}},normativeVersion:'n1'}),fp); assert.notEqual(createCorrectionFingerprint({assessment:{...r,birthDate:'2020-02-01'},normativeVersion:'n1'}),fp); assert.notEqual(createCorrectionFingerprint({assessment:{...r,manualAgeOverride:true,ageMonths:50},normativeVersion:'n1'}),fp); assert.equal(createCorrectionFingerprint({assessment:{...r,name:'Otro'},normativeVersion:'n1'}),fp); assert.equal(createCorrectionFingerprint({assessment:{...r,observations:{A1:'b'}},normativeVersion:'n1'}),fp);});
test('error de cuota, no DOM ni funciones serializadas, nueva no elimina anterior, volver guarda primero', async()=>{const fail=new Mem(true); await assert.rejects(saveAssessment(createAssessmentRecord({id:'bat-x1'}),fail),/quota/); const s=new Mem; const r=createAssessmentRecord({id:'bat-x1',extra:()=>{},node:{nodeType:1}}); await saveAssessment(r,s); const raw=s.getItem(ASSESSMENTS_KEY); assert.equal(raw.includes('nodeType'),false); await saveAssessment(createAssessmentRecord({id:'bat-x2'}),s); assert.equal((await listAssessments(s)).length,2);});
test('evento storage se puede identificar por clave de colección',()=>{assert.equal(ASSESSMENTS_KEY,'battelleAssessmentsV3');});
test('reconstrucción única del resultado se apoya en metadata mínima',()=>{const r=createAssessmentRecord({id:'bat-ok',workflowStatus:WORKFLOW_STATUS.CORRECTED,correctionMetadata:{fingerprint:'fp',normativeId:'norm',dataVersion:'items-v1',modelVersion:'model-v1'}}); assert.deepEqual(Object.keys(r.correctionMetadata).sort(),['dataVersion','fingerprint','modelVersion','normativeId']);});
