import { loadAndNormalizeItems } from './src/battelle-data.js';
import { loadScaleModel, validateScaleModel } from './src/battelle-scales.js';
import { scoreAssessment } from './src/battelle-scoring.js';
import { runCorrection, isCorrectionStale } from './src/battelle-correction.js';
import { loadJson } from './src/battelle-data.js';
import { NORMATIVE_ERROR_MESSAGE, ageBandForMonths, loadNormativeData, validateNormativeData } from './src/battelle-conversions.js';
import { createAssessment, hasAssessmentChanges, calculateAgeMonths, formatAge, persistAssessment, loadStoredAssessment, LEGACY_KEY, STORAGE_KEY } from './src/battelle-state.js';

const $ = (id) => document.getElementById(id);
const state = { ready:false, items:[], model:null, normativeData:null, normativeValidation:null, assessment:null, score:null, correction:null, evaluationStatus:'administrando', activeArea:'Personal/Social' };
const scaleOrder = ['personal_social_total','adaptativa_total','motora_gruesa','motora_fina','motora_total','comunicacion_receptiva','comunicacion_expresiva','comunicacion_total','cognitiva_total','battelle_total'];
const areas = ['Personal/Social','Adaptativa','Motora','Comunicación','Cognitiva'];
function el(tag, attrs={}, ...children){ const n=document.createElement(tag); for(const [k,v] of Object.entries(attrs)){ if(k==='class') n.className=v; else if(k.startsWith('aria')) n.setAttribute(k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()), v); else if(k==='dataset') Object.assign(n.dataset,v); else if(k==='for') n.htmlFor=v; else n[k]=v; } for(const c of children) n.append(c?.nodeType?c:document.createTextNode(String(c))); return n; }
function setText(id, text){ $(id).textContent = text; }
function currentAge(){ if (!state.assessment) return null; if (state.assessment.manualAgeOverride) return state.assessment.ageMonths; const r=calculateAgeMonths(state.assessment.birthDate,state.assessment.assessmentDate); return r.ok ? r.months : null; }
function updateAge(){ const a=state.assessment; const r=calculateAgeMonths(a.birthDate,a.assessmentDate); if(!a.manualAgeOverride) a.ageMonths=r.ok?r.months:null; const manualInvalid=a.manualAgeOverride && !Number.isInteger(a.ageMonths); const band=ageBandForMonths(a.ageMonths); const msg=manualInvalid?'La anulación manual de edad está vacía o fuera de 0–95 meses.':(r.ok||a.manualAgeOverride ? `${formatAge(a.ageMonths)} · tramo ${band?.label ?? 'fuera de baremo'}` : r.message); setText('ageBandLabel', msg); $('ageMonths').value = a.ageMonths ?? ''; return !manualInvalid && (a.manualAgeOverride ? Number.isInteger(a.ageMonths) : r.ok); }
function save(){ if(state.assessment) persistAssessment(localStorage,state.assessment); }
function hasBlockingScoreError(){ return (state.correction?.errors ?? []).length > 0; }
function conversionsAllowed(){ return state.evaluationStatus==='corregida' && !hasBlockingScoreError() && updateAge(); }
function resetCorrection(next='administrando'){ state.score=null; state.correction=null; state.evaluationStatus=next; updateResults(); updateVisibleItemsEffective(); save(); }
function maybeInvalidateCorrection(changedScoringData=true){ if(!changedScoringData){ save(); updateResults(); return; } if(state.correction && isCorrectionStale({assessment:state.assessment, correction:state.correction})){ state.score=null; state.correction=null; state.evaluationStatus='resultado_desactualizado'; } else if(state.evaluationStatus!=='correccion_bloqueada') state.evaluationStatus='administrando'; updateResults(); updateVisibleItemsEffective(); save(); }
function startNew(force=false){ if(!state.ready) return; if(!force && hasAssessmentChanges(state.assessment) && !confirm('Hay cambios en la evaluación activa. ¿Crear una nueva Battelle y descartar el borrador actual?')) return; state.assessment=createAssessment(); state.score=null; $('welcomeView').classList.add('hidden'); $('assessmentView').classList.remove('hidden'); bindAssessment(); renderAreas(); renderItems(); resetCorrection('administrando'); $('patientName').focus(); }
function bindAssessment(){ const a=state.assessment; $('patientName').value=a.name; $('birthDate').value=a.birthDate; $('assessmentDate').value=a.assessmentDate; $('manualAgeOverride').checked=!!a.manualAgeOverride; updateAge(); }
function onMeta(e){ const a=state.assessment; if(!a) return; if(e.target.id==='patientName') a.name=e.target.value; if(e.target.id==='birthDate') a.birthDate=e.target.value; if(e.target.id==='assessmentDate') a.assessmentDate=e.target.value; if(e.target.id==='manualAgeOverride'){ a.manualAgeOverride=e.target.checked; if(a.manualAgeOverride && !Number.isInteger(a.ageMonths)){ const r=calculateAgeMonths(a.birthDate,a.assessmentDate); a.ageMonths=r.ok?r.months:null; } } if(e.target.id==='ageMonths'){ a.manualAgeOverride=true; $('manualAgeOverride').checked=true; const v=e.target.value===''?null:Number(e.target.value); a.ageMonths=Number.isInteger(v)&&v>=0&&v<=95?v:null; } a.updatedAt=new Date().toISOString(); updateAge(); maybeInvalidateCorrection(e.target.id!=='patientName'); }
function renderAreas(){ const nav=$('areaNav'); nav.replaceChildren(...areas.map(area=>el('button',{class:`area-tab ${area===state.activeArea?'active':''}`, ariaPressed:String(area===state.activeArea), dataset:{area}}, area, ` (${state.items.filter(i=>i.area===area).length})`))); }
function renderItems(){ const container=$('itemsContainer'); const bySub=new Map(); for(const item of state.items.filter(i=>i.area===state.activeArea)){ const k=item.subarea; if(!bySub.has(k)) bySub.set(k,[]); bySub.get(k).push(item); } const sections=[]; for(const [sub, items] of bySub){ sections.push(el('section',{class:'subarea-card', dataset:{subarea:sub}}, el('h3',{},sub), el('div',{class:'subarea-summary', dataset:{summary:sub}}), ...items.map(renderItem))); } container.replaceChildren(...sections); updateResults(); updateVisibleItemsEffective(); }
function confidenceInfo(value){ if(value==='visual_alta') return {className:'confidence high', label:'Confianza visual alta'}; if(value==='visual_media') return {className:'confidence medium', label:'Confianza visual media'}; return {className:'confidence warn', label:'Revisión visual recomendada'}; }
function renderItem(item){ const obs=state.assessment?.observedResponses?.[item.codigo_canonico]; const confidence=confidenceInfo(item.confianza); const buttons=[null,0,1,2].map(v=>el('button',{type:'button', class:'score-btn', ariaPressed:String((obs??null)===v), dataset:{code:item.codigo_canonico, score:v===null?'null':String(v)}}, v===null?'No administrado':String(v))); return el('article',{class:'item-card', dataset:{code:item.codigo_canonico, min:item.rango_edad_min_meses, max:item.rango_edad_max_meses}}, el('div',{class:'item-head'}, el('strong',{},item.codigo), el('span',{},`Edad ${item.rango_edad}`), el('span',{class:confidence.className},confidence.label)), el('p',{},item.enunciado), el('div',{class:'score-controls'},...buttons), el('p',{class:'effective hidden', dataset:{effective:item.codigo_canonico}}, 'Puntuación derivada pendiente de corrección'), el('label',{}, 'Observación', el('textarea',{dataset:{obs:item.codigo_canonico}, value:state.assessment?.observations?.[item.codigo_canonico] ?? '', rows:2})) ); }
function updateVisibleItemsEffective(){ const show=state.evaluationStatus==='corregida'; const eff=state.score?.respuestas_efectivas ?? {}; for(const node of document.querySelectorAll('[data-effective]')){ node.classList.toggle('hidden', !show); const code=node.dataset.effective; const r=eff[code]; node.textContent = !show ? '' : (r?.puntuacion===null ? 'Puntuación efectiva: no administrado' : `Puntuación efectiva: ${r.puntuacion} · ${r.origen==='observado'?'Observado':r.origen==='basal'?'Derivado por basal':'Derivado por techo'}`); } for(const card of document.querySelectorAll('.item-card')){ const r=eff[card.dataset.code]; card.dataset.origin = show ? (r?.origen ?? 'no_administrado') : 'observado'; } }
function statusLabel(){ return {administrando:'Administrando', corrigiendo:'Corrigiendo', corregida:'Corregida', resultado_desactualizado:'Resultado desactualizado', correccion_bloqueada:'Corrección bloqueada'}[state.evaluationStatus]; }
function observedProgress(){ const total=state.items.length; const answered=Object.keys(state.assessment?.observedResponses??{}).length; return {total, answered, notAdmin:total-answered}; }
function correctEnabled(){ return state.ready && state.normativeValidation?.ok && state.assessment && Number.isInteger(currentAge()) && Object.keys(state.assessment.observedResponses??{}).length>0; }
function gotoItem(code){ const item=state.items.find(i=>i.codigo_canonico===code); if(!item) return; state.activeArea=item.area; renderAreas(); renderItems(); setTimeout(()=>{ const card=document.querySelector(`[data-code="${code}"]`); card?.scrollIntoView({block:'center'}); card?.querySelector('button,textarea')?.focus(); card?.classList.add('highlight'); setTimeout(()=>card?.classList.remove('highlight'),1800); }, 0); }
function adminPanel(message='') { const p=observedProgress(); const byArea=areas.map(a=>`${a}: ${Object.keys(state.assessment?.observedResponses??{}).filter(c=>state.items.find(i=>i.codigo_canonico===c)?.area===a).length}/${state.items.filter(i=>i.area===a).length}`).join(' · '); return el('section',{class:'summary-card'}, el('h2',{},statusLabel()), message?el('p',{class:'warning'},message):'', el('p',{},`Progreso observado total: ${p.answered}/${p.total}`), el('p',{},`Respondidos: ${p.answered}; no administrados: ${p.notAdmin}`), el('p',{},byArea), state.normativeValidation?.ok===false?el('p',{class:'error',role:'alert'},NORMATIVE_ERROR_MESSAGE):'', el('button',{type:'button', id:'correctBtn', class:'primary-button', disabled:!correctEnabled()},'Corregir Battelle')); }
function blockedPanel(){ const c=state.correction; const items=c?.pendingReport?.items??[]; return el('section',{class:'error-block', role:'alert'}, el('h2',{},'Corrección bloqueada'), el('p',{},'No se muestran resultados hasta resolver los problemas. No se muestran PD válidas ni conversiones.'), el('ul',{},...(c?.errors??[]).map(err=>el('li',{},err.message))), items.length?el('div',{}, el('h3',{},`Ítems pendientes (${items.length})`), el('p',{},`Por área: ${Object.entries(c.pendingReport.byArea).map(([k,v])=>`${k}: ${v}`).join(' · ')}`), el('ul',{},...items.map(p=>el('li',{},`${p.code} · ${p.area} · ${p.subarea} · ${p.ageRange} · ${p.reason} · ${p.statement} `, el('button',{type:'button', class:'link-button goto-item', dataset:{code:p.code}},'Ir al ítem'))))):''); }
function safeText(value, fallback='—'){ if(value===undefined||value===null) return fallback; if(typeof value==='object') return fallback; const text=String(value); return /undefined|null|\[object Object\]/i.test(text)?fallback:text; }
function displayDate(value){ return safeText(value,'Sin fecha'); }
function patientLabel(value){ const text=safeText(value,'').trim(); return text||'Sin identificar'; }
function showNorm(value, none='—'){ if(!value) return '—'; if(value.ok) return safeText(value.percentile ?? value.centile ?? value.text, '—'); const labels={no_aplicable:'—',fuera_rango_normativo:'Fuera de rango',no_alcanzable:'No alcanzable',error_baremos:'Baremo no encontrado',error_datos:'Error de datos',incompleto:'Incompleto'}; return labels[value.status] ?? labels[value.error?.code] ?? none; }
function technicalHint(value, kind='conversión'){ if(!value) return `${kind}: no aplicable.`; if(value.ok) return `${kind} localizada en ${sourceLine(value)}.`; const code=value.status ?? value.error?.code; const labels={no_aplicable:'Esta conversión no se aplica a esta fila.',escala_no_incluida:'No existe conversión normativa para esta escala.',fuera_rango_normativo:'La PD queda fuera del rango normativo disponible.',pd_fuera_de_rango:'La PD queda fuera del rango normativo disponible.',no_alcanzable:'La PD no es alcanzable según la incidencia normativa.',pd_no_alcanzable:'La PD no es alcanzable según la incidencia normativa.',error_baremos:'No se encontró un baremo único.',baremo_no_encontrado:'No se encontró un baremo único.',error_datos:'Dato no válido para convertir.',pd_invalida:'Dato no válido para convertir.'}; return labels[code] ?? 'Conversión no disponible.'; }
function eqLabel(eq){ if(!eq) return '—'; if(eq.ok) return eq.minMonths===eq.maxMonths?`${eq.text} meses`:eq.text; return '—'; }
function sourceLine(x){ const s=x?.source||x?.provenance; if(!s) return 'Sin procedencia'; const parts=[x.table,s.archivo?.split('/').pop(),s.hoja?`hoja ${s.hoja}`:null,s.celda?`celda ${s.celda}`:null,s.columna?`columna ${s.columna}`:null].filter(Boolean); return parts.length?parts.join(' · '):'Sin procedencia'; }
function td(text, attrs={}){ return el('td',attrs,safeText(text)); }
function th(text, attrs={}){ return el('th',attrs,text); }
function metricCard(label,value,attrs={}){ return el('article',{class:'metric-card'}, el('span',{class:'metric-label'},label), el('strong',{...attrs},safeText(value))); }
function info(label,title){ return el('span',{class:'info-chip', title, tabindex:0, ariaLabel:`Información sobre ${label}`},label); }
function compactDetails(counts){ if(!counts) return '—'; const title=`Observadas: ${counts.observed}; derivadas por basal: ${counts.derivedByBasal}; derivadas por techo: ${counts.derivedByCeiling}`; return el('span',{class:'admin-counts',title},`Obs. ${counts.observed} · Basal ${counts.derivedByBasal} · Techo ${counts.derivedByCeiling}`); }
function areaRows(r){ const ids=[['Personal/Social','personal_social_total'],['Adaptativa','adaptativa_total'],['Motora','motora_total'],['Comunicación','comunicacion_total'],['Cognitiva','cognitiva_total']]; return ids.map(([name,id])=>({name,id,s:r.scales[id]})).filter(x=>x.s); }
function needsWarning(s){ return (s.percentile&&!s.percentile.ok&&s.percentile.status!=='no_aplicable')||(s.equivalentAge&&!s.equivalentAge.ok&&s.equivalentAge.error?.code!=='escala_no_incluida'); }
function renderTable(headers, rows, className='results-table'){ return el('div',{class:'table-wrap'}, el('table',{class:className}, el('thead',{},el('tr',{},...headers.map(h=>th(h)))), el('tbody',{},...rows))); }
function areaTotalsTable(r){ const rows=areaRows(r); const warn=rows.some(({s})=>needsWarning(s)); return renderTable(['Área','PD','Percentil','Edad equivalente',...(warn?['Aviso']:[])], rows.map(({name,s})=>el('tr',{}, td(name), td(s.pd,{class:'num'}), td(showNorm(s.percentile),{class:'num',title:technicalHint(s.percentile,'Percentil')}), td(eqLabel(s.equivalentAge),{class:'num',title:technicalHint(s.equivalentAge,'Edad equivalente')}), ...(warn?[td(needsWarning(s)?technicalHint(s.equivalentAge&&!s.equivalentAge.ok?s.equivalentAge:s.percentile,'Aviso'):'—')]:[])))); }
function subareaSections(r){ const aggregateByArea={Motora:['motora_gruesa','motora_fina'],Comunicación:['comunicacion_receptiva','comunicacion_expresiva']}; return areas.map(area=>{ const subs=Object.values(r.subareas).filter(s=>s.area===area).sort((a,b)=>(a.subarea||'').localeCompare(b.subarea||'')); const aggs=(aggregateByArea[area]??[]).map(id=>r.scales[id]).filter(Boolean).map(s=>({...s, subarea:s.name, aggregate:true})); const rows=[...subs,...aggs].map(s=>el('tr',{}, td(s.aggregate?`${s.subarea} (agregado)`:s.subarea), td(s.pd,{class:'num'}), td(showNorm(s.percentile),{class:'num',title:technicalHint(s.percentile,'Percentil')}), td(eqLabel(s.equivalentAge),{class:'num',title:technicalHint(s.equivalentAge,'Edad equivalente')}), el('td',{},compactDetails(s.counts)))); return el('details',{class:'subarea-section'}, el('summary',{},`${area} · ${subs.length} subáreas${aggs.length?` · ${aggs.length} agregados`:''}`), renderTable(['Subárea o agregado','PD','Percentil','Edad equivalente','Administración'], rows, 'results-table compact')); }); }
function provenanceBlock(r){ const entries=[r.summary.totalCentile,r.summary.generalConversion,r.summary.totalEquivalentAge,...Object.values(r.scales).flatMap(s=>[s.percentile,s.equivalentAge].filter(Boolean)),...Object.values(r.subareas).flatMap(s=>[s.percentile].filter(Boolean))].filter(Boolean); const unique=[...new Map(entries.map(x=>[sourceLine(x),x])).values()]; return el('details',{class:'technical-block'}, el('summary',{},'Información técnica y procedencia normativa'), el('p',{},`Versión normativa: ${safeText(r.normative.version)} · ${safeText(r.normative.id)}`), el('ul',{},...unique.map(x=>el('li',{},sourceLine(x))))); }
function resultsView(){ const r=state.correction.results; const gc=r.summary.generalConversion; const tc=r.summary.totalCentile; const totalEq=r.summary.totalEquivalentAge; return el('section',{class:'results-view'}, el('header',{class:'results-header'}, el('div',{}, el('h2',{},'Resultados de la evaluación'), el('p',{class:'muted'},`${patientLabel(r.metadata.name)} · Evaluación: ${displayDate(r.metadata.assessmentDate)} · Nacimiento: ${displayDate(r.metadata.birthDate)}`), el('p',{class:'muted'},`Edad cronológica: ${formatAge(r.summary.ageMonths)}`)), el('div',{class:'results-actions'}, el('button',{type:'button', id:'editScoresBtn', class:'secondary-button'},'Editar puntuaciones'), el('button',{type:'button', class:'secondary-button disabled-action', disabled:true, title:'Pendiente de implementación'},'Descargar PDF'))), el('section',{class:'summary-band',ariaLabel:'Resumen general'}, el('div',{class:'primary-metrics'}, metricCard('Edad cronológica',formatAge(r.summary.ageMonths)), metricCard('PD total Battelle',r.summary.directScoreTotal,{class:'num'}), metricCard('Centil total',showNorm(tc),{class:'num',title:technicalHint(tc,'Centil total')}), metricCard('Edad equivalente total',eqLabel(totalEq),{class:'num',title:technicalHint(totalEq,'Edad equivalente total')})), el('div',{class:'secondary-metrics'}, el('span',{},info('z','Puntuación típica z derivada del centil total.'),' ',safeText(gc.ok?gc.z:'—')), el('span',{},info('T','Puntuación T derivada del centil total.'),' ',safeText(gc.ok?gc.T:'—')), el('span',{},info('CI','Cociente intelectual normativo derivado del centil total.'),' ',safeText(gc.ok?gc.CI:'—')), el('span',{},info('ECN','Edad cronológica normativa derivada del centil total.'),' ',safeText(gc.ok?gc.ECN:'—')))), el('section',{class:'report-section'}, el('h3',{},'Totales de área'), areaTotalsTable(r)), el('section',{class:'report-section'}, el('h3',{},'Subáreas y agregados'), ...subareaSections(r)), el('p',{class:'clinical-note'},'Los resultados deben interpretarse conjuntamente con la información clínica y el criterio profesional.'), provenanceBlock(r)); }
function updateResults(){ const panel=$('resultsPanel'); const corrected=state.evaluationStatus==='corregida'; $('areaNav').classList.toggle('hidden', corrected); $('itemsContainer').classList.toggle('hidden', corrected); if(!state.assessment){ panel.replaceChildren(); return; } if(state.evaluationStatus==='corregida' && state.correction && !isCorrectionStale({assessment:state.assessment, correction:state.correction})) panel.replaceChildren(resultsView()); else if(state.evaluationStatus==='correccion_bloqueada') panel.replaceChildren(adminPanel(), blockedPanel()); else if(state.evaluationStatus==='resultado_desactualizado') panel.replaceChildren(adminPanel('La evaluación ha cambiado. Vuelve a pulsar Corregir Battelle.')); else panel.replaceChildren(adminPanel()); }
function runUiCorrection(){ state.evaluationStatus='corrigiendo'; updateResults(); const result=runCorrection({assessment:state.assessment,items:state.items,model:state.model,normativeData:state.normativeData,scoreAssessment}); state.correction=result; state.score=result.scoring; state.evaluationStatus=result.status; updateResults(); updateVisibleItemsEffective(); save(); }
async function init(){ try{ setText('loadStatus','Cargando datos Battelle…'); const [items,model,normativeData]=await Promise.all([loadAndNormalizeItems(),loadScaleModel(),loadNormativeData(loadJson)]); validateScaleModel(model,items); const normativeValidation=validateNormativeData(normativeData,model); Object.assign(state,{ready:true,items,model,normativeData,normativeValidation}); $('newAssessmentBtn').disabled=false; setText('loadStatus',`Datos cargados: ${items.length} ítems, ${Object.keys(model.subareas).length} subáreas y ${Object.keys(model.escalas).length} escalas. ${normativeValidation.ok?'Baremos normativos válidos.':NORMATIVE_ERROR_MESSAGE}`); const stored=loadStoredAssessment(localStorage); if(stored.legacyDetected) $('legacyNotice').classList.remove('hidden'); if(!stored.current.ok && !['empty','version_incompatible'].includes(stored.current.reason)){ $('draftNotice').classList.remove('hidden'); setText('draftNoticeText', `Se detectó un borrador V2 inválido (${stored.current.reason}). No se abrirá automáticamente.`); } if(stored.current.ok){ state.assessment=stored.current.assessment; $('welcomeView').classList.add('hidden'); $('assessmentView').classList.remove('hidden'); bindAssessment(); renderAreas(); renderItems(); resetCorrection('administrando'); } } catch(err){ $('loadStatus').className='error'; setText('loadStatus',`Error bloqueante al cargar recursos: ${err.message}`); $('newAssessmentBtn').disabled=true; }}
document.addEventListener('click',(e)=>{ if(e.target.id==='newAssessmentBtn') startNew(); if(e.target.id==='discardLegacyBtn'){ localStorage.removeItem(LEGACY_KEY); $('legacyNotice').classList.add('hidden'); } if(e.target.id==='discardDraftBtn'){ localStorage.removeItem(STORAGE_KEY); $('draftNotice').classList.add('hidden'); startNew(true); } if(e.target.id==='discardInvalidBtn'){ localStorage.removeItem(STORAGE_KEY); startNew(true); } if(e.target.id==='correctBtn') runUiCorrection(); if(e.target.id==='editScoresBtn') resetCorrection('administrando'); if(e.target.matches('.goto-item')) gotoItem(e.target.dataset.code); if(e.target.matches('.area-tab')){ state.activeArea=e.target.dataset.area; renderAreas(); renderItems(); } if(e.target.matches('.score-btn')){ const code=e.target.dataset.code; const v=e.target.dataset.score==='null'?null:Number(e.target.dataset.score); if(v===null) delete state.assessment.observedResponses[code]; else state.assessment.observedResponses[code]=v; document.querySelectorAll(`.score-btn[data-code="${code}"]`).forEach(b=>b.setAttribute('aria-pressed', String(b===e.target))); maybeInvalidateCorrection(true); }});
document.addEventListener('input',(e)=>{ if(['patientName','birthDate','assessmentDate','ageMonths'].includes(e.target.id)) onMeta(e); if(e.target.matches('textarea[data-obs]')){ state.assessment.observations[e.target.dataset.obs]=e.target.value; maybeInvalidateCorrection(false); }}); document.addEventListener('change',(e)=>{ if(e.target.id==='manualAgeOverride') onMeta(e); });
init();
