import { loadAndNormalizeItems } from './src/battelle-data.js';
import { loadScaleModel, validateScaleModel } from './src/battelle-scales.js';
import { scoreAssessment } from './src/battelle-scoring.js';
import { loadJson } from './src/battelle-data.js';
import { ageBandForMonths, percentileForScale, equivalentAgeForScale, validatePercentileMappings } from './src/battelle-conversions.js';
import { createAssessment, hasAssessmentChanges, calculateAgeMonths, formatAge, persistAssessment, loadStoredAssessment, LEGACY_KEY, STORAGE_KEY } from './src/battelle-state.js';

const $ = (id) => document.getElementById(id);
const state = { ready:false, items:[], model:null, percentiles:null, equivalentAges:null, assessment:null, score:null, activeArea:'Personal/Social' };
const scaleOrder = ['personal_social_total','adaptativa_total','motora_gruesa','motora_fina','motora_total','comunicacion_receptiva','comunicacion_expresiva','comunicacion_total','cognitiva_total','battelle_total'];
const areas = ['Personal/Social','Adaptativa','Motora','Comunicación','Cognitiva'];
function el(tag, attrs={}, ...children){ const n=document.createElement(tag); for(const [k,v] of Object.entries(attrs)){ if(k==='class') n.className=v; else if(k.startsWith('aria')) n.setAttribute(k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()), v); else if(k==='dataset') Object.assign(n.dataset,v); else if(k==='for') n.htmlFor=v; else n[k]=v; } for(const c of children) n.append(c?.nodeType?c:document.createTextNode(String(c))); return n; }
function setText(id, text){ $(id).textContent = text; }
function currentAge(){ if (!state.assessment) return null; if (state.assessment.manualAgeOverride) return state.assessment.ageMonths; const r=calculateAgeMonths(state.assessment.birthDate,state.assessment.assessmentDate); return r.ok ? r.months : null; }
function updateAge(){ const a=state.assessment; const r=calculateAgeMonths(a.birthDate,a.assessmentDate); if(!a.manualAgeOverride) a.ageMonths=r.ok?r.months:null; const manualInvalid=a.manualAgeOverride && !Number.isInteger(a.ageMonths); const band=ageBandForMonths(a.ageMonths); const msg=manualInvalid?'La anulación manual de edad está vacía o fuera de 0–95 meses.':(r.ok||a.manualAgeOverride ? `${formatAge(a.ageMonths)} · tramo ${band?.label ?? 'fuera de baremo'}` : r.message); setText('ageBandLabel', msg); $('ageMonths').value = a.ageMonths ?? ''; return !manualInvalid && (a.manualAgeOverride ? Number.isInteger(a.ageMonths) : r.ok); }
function save(){ if(state.assessment) persistAssessment(localStorage,state.assessment); }
function hasBlockingScoreError(){ return (state.score?.errores ?? []).length > 0; }
function conversionsAllowed(){ return !hasBlockingScoreError() && updateAge(); }
function rescore(){ state.score = scoreAssessment(state.items, state.model, state.assessment?.observedResponses ?? {}); updateResults(); updateVisibleItemsEffective(); save(); }
function startNew(force=false){ if(!state.ready) return; if(!force && hasAssessmentChanges(state.assessment) && !confirm('Hay cambios en la evaluación activa. ¿Crear una nueva Battelle y descartar el borrador actual?')) return; state.assessment=createAssessment(); state.score=null; $('welcomeView').classList.add('hidden'); $('assessmentView').classList.remove('hidden'); bindAssessment(); renderAreas(); renderItems(); rescore(); $('patientName').focus(); }
function bindAssessment(){ const a=state.assessment; $('patientName').value=a.name; $('birthDate').value=a.birthDate; $('assessmentDate').value=a.assessmentDate; $('manualAgeOverride').checked=!!a.manualAgeOverride; updateAge(); }
function onMeta(e){ const a=state.assessment; if(!a) return; if(e.target.id==='patientName') a.name=e.target.value; if(e.target.id==='birthDate') a.birthDate=e.target.value; if(e.target.id==='assessmentDate') a.assessmentDate=e.target.value; if(e.target.id==='manualAgeOverride'){ a.manualAgeOverride=e.target.checked; if(a.manualAgeOverride && !Number.isInteger(a.ageMonths)){ const r=calculateAgeMonths(a.birthDate,a.assessmentDate); a.ageMonths=r.ok?r.months:null; } } if(e.target.id==='ageMonths'){ a.manualAgeOverride=true; $('manualAgeOverride').checked=true; const v=e.target.value===''?null:Number(e.target.value); a.ageMonths=Number.isInteger(v)&&v>=0&&v<=95?v:null; } a.updatedAt=new Date().toISOString(); updateAge(); rescore(); }
function renderAreas(){ const nav=$('areaNav'); nav.replaceChildren(...areas.map(area=>el('button',{class:`area-tab ${area===state.activeArea?'active':''}`, ariaPressed:String(area===state.activeArea), dataset:{area}}, area, ` (${state.items.filter(i=>i.area===area).length})`))); }
function renderItems(){ const container=$('itemsContainer'); const bySub=new Map(); for(const item of state.items.filter(i=>i.area===state.activeArea)){ const k=item.subarea; if(!bySub.has(k)) bySub.set(k,[]); bySub.get(k).push(item); } const sections=[]; for(const [sub, items] of bySub){ sections.push(el('section',{class:'subarea-card', dataset:{subarea:sub}}, el('h3',{},sub), el('div',{class:'subarea-summary', dataset:{summary:sub}}), ...items.map(renderItem))); } container.replaceChildren(...sections); updateResults(); updateVisibleItemsEffective(); }
function confidenceInfo(value){ if(value==='visual_alta') return {className:'confidence high', label:'Confianza visual alta'}; if(value==='visual_media') return {className:'confidence medium', label:'Confianza visual media'}; return {className:'confidence warn', label:'Revisión visual recomendada'}; }
function renderItem(item){ const obs=state.assessment?.observedResponses?.[item.codigo_canonico]; const confidence=confidenceInfo(item.confianza); const buttons=[null,0,1,2].map(v=>el('button',{type:'button', class:'score-btn', ariaPressed:String((obs??null)===v), dataset:{code:item.codigo_canonico, score:v===null?'null':String(v)}}, v===null?'No administrado':String(v))); return el('article',{class:'item-card', dataset:{code:item.codigo_canonico, min:item.rango_edad_min_meses, max:item.rango_edad_max_meses}}, el('div',{class:'item-head'}, el('strong',{},item.codigo), el('span',{},`Edad ${item.rango_edad}`), el('span',{class:confidence.className},confidence.label)), el('p',{},item.enunciado), el('div',{class:'score-controls'},...buttons), el('p',{class:'effective', dataset:{effective:item.codigo_canonico}}, 'Efectiva: no administrado'), el('label',{}, 'Observación', el('textarea',{dataset:{obs:item.codigo_canonico}, value:state.assessment?.observations?.[item.codigo_canonico] ?? '', rows:2})) ); }
function updateVisibleItemsEffective(){ const eff=state.score?.respuestas_efectivas ?? {}; for(const node of document.querySelectorAll('[data-effective]')){ const code=node.dataset.effective; const r=eff[code]; node.textContent = r?.puntuacion===null ? 'Efectiva: no administrado · origen: No administrado' : `Efectiva: ${r.puntuacion} · origen: ${r.origen==='observado'?'Observado':r.origen==='basal'?'Derivado por basal':'Derivado por techo'}`; } for(const card of document.querySelectorAll('.item-card')){ const r=eff[card.dataset.code]; card.dataset.origin = r?.origen ?? 'no_administrado'; } }
function percentileMessage(result, age){ if(!result) return 'Pendiente'; if(result.ok) return `Percentil ${result.percentile} · ${result.table} p.${result.page}`; if(result.error.code==='escala_no_encontrada') return 'Escala no incluida en este tramo'; if(result.error.code==='tramo_no_disponible' || age>35) return 'Percentiles pendientes de normalización'; return `Percentil no disponible: ${result.error.message}`; }
function updateResults(){ if(!state.score) return; const age=currentAge(); const panel=$('resultsPanel'); if(hasBlockingScoreError()){ panel.replaceChildren(el('section',{class:'error-block', role:'alert'}, el('h2',{},'Errores del motor de puntuación'), el('p',{},'El borrador necesita corrección o descarte. No se muestran PD válidas ni conversiones.'), el('ul',{},...state.score.errores.map(err=>el('li',{},err.mensaje))), el('button',{type:'button', class:'secondary-button', id:'discardInvalidBtn'},'Descartar borrador inválido y crear evaluación limpia'))); return; } const global=el('section',{class:'summary-card'}, el('h2',{},'Resumen global'), el('p',{},`Edad cronológica: ${formatAge(age)}`), el('p',{},`Progreso observado: ${Object.keys(state.assessment.observedResponses).length}/341`), el('p',{},`Progreso efectivo: ${Object.values(state.score.respuestas_efectivas).filter(r=>r.puntuacion!==null).length}/341`), el('p',{},`Subáreas completas: ${Object.values(state.score.subareas).filter(s=>s.completa).length}/${Object.keys(state.score.subareas).length}`), el('p',{},`Inconsistencias: ${state.score.inconsistencias.length}`)); const scaleList=el('div',{class:'scale-grid'}); for(const id of scaleOrder){ const s=state.score.escalas[id]; if(!s) continue; const allowConv=conversionsAllowed(); const pct= allowConv && s.pd!==null && !s.requiere_revision ? percentileForScale({ageMonths:age,scaleId:id,directScore:s.pd,percentileData:state.percentiles,requiresReview:s.requiere_revision,maxScore:s.maximo}) : null; const eq= allowConv && s.pd!==null && !s.requiere_revision ? equivalentAgeForScale({scaleId:id,directScore:s.pd,equivalentAgeData:state.equivalentAges,requiresReview:s.requiere_revision,maxScore:s.maximo}) : null; scaleList.append(el('article',{class:'scale-card'}, el('h3',{},state.model.escalas[id].nombre), el('p',{},`PD: ${s.pd===null?'Pendiente':s.pd} (parcial ${s.pd_parcial}/${s.maximo})`), el('p',{},s.requiere_revision?'Requiere revisión':s.pendientes.length?`Pendiente por ${s.pendientes.length} ítems`:'Resultado válido'), el('p',{}, percentileMessage(pct, age)), el('p',{}, eq?.ok ? `Edad equivalente: ${eq.minMonths===eq.maxMonths?eq.minMonths:`${eq.minMonths}-${eq.maxMonths}`} meses · ${eq.table}` : 'Edad equivalente pendiente'))); }
 const subList=el('div',{class:'subarea-results'}); for(const [id,s] of Object.entries(state.score.subareas).filter(([,s])=>s.area===state.activeArea)){ subList.append(el('article',{class:'sub-result'}, el('h3',{},s.subarea), el('p',{},`PD parcial ${s.pd_parcial}; PD válida ${s.pd===null?'Pendiente':s.pd}; máximo ${s.maximo}`), el('p',{},`Basal: ${s.basal.confirmado?`${s.basal.inicio}-${s.basal.fin}`:'no confirmado'} · Techo: ${s.techo.confirmado?`${s.techo.inicio}-${s.techo.fin}${s.techo.provisional?' provisional':''}`:'no confirmado'}`), el('p',{},`Pendientes ${s.pendientes.length}; revisión ${s.requiere_revision?'sí':'no'}`), el('p',{}, s.requiere_revision?'Requiere revisión':(s.pd===null?'Percentil: Pendiente':`Percentil: ${percentileMessage(conversionsAllowed()?percentileForScale({ageMonths:age,scaleId:id,directScore:s.pd,percentileData:state.percentiles,requiresReview:s.requiere_revision,maxScore:s.maximo}):null, age)}`)), ...s.inconsistencias.map(w=>el('p',{class:'warning'},w.mensaje)))); } panel.replaceChildren(global, scaleList, el('h2',{},`Subáreas de ${state.activeArea}`), subList); }
async function init(){ try{ setText('loadStatus','Cargando datos Battelle…'); const [items,model,percentiles,equivalentAges]=await Promise.all([loadAndNormalizeItems(),loadScaleModel(),loadJson('data/percentiles_battelle.json'),loadJson('data/edades_equivalentes.json')]); validateScaleModel(model,items); validatePercentileMappings(model,percentiles); Object.assign(state,{ready:true,items,model,percentiles,equivalentAges}); $('newAssessmentBtn').disabled=false; setText('loadStatus',`Datos cargados: ${items.length} ítems, ${Object.keys(model.subareas).length} subáreas y ${Object.keys(model.escalas).length} escalas.`); const stored=loadStoredAssessment(localStorage); if(stored.legacyDetected) $('legacyNotice').classList.remove('hidden'); if(!stored.current.ok && !['empty','version_incompatible'].includes(stored.current.reason)){ $('draftNotice').classList.remove('hidden'); setText('draftNoticeText', `Se detectó un borrador V2 inválido (${stored.current.reason}). No se abrirá automáticamente.`); } if(stored.current.ok){ state.assessment=stored.current.assessment; $('welcomeView').classList.add('hidden'); $('assessmentView').classList.remove('hidden'); bindAssessment(); renderAreas(); renderItems(); rescore(); } } catch(err){ $('loadStatus').className='error'; setText('loadStatus',`Error bloqueante al cargar recursos: ${err.message}`); $('newAssessmentBtn').disabled=true; }}
document.addEventListener('click',(e)=>{ if(e.target.id==='newAssessmentBtn') startNew(); if(e.target.id==='discardLegacyBtn'){ localStorage.removeItem(LEGACY_KEY); $('legacyNotice').classList.add('hidden'); } if(e.target.id==='discardDraftBtn'){ localStorage.removeItem(STORAGE_KEY); $('draftNotice').classList.add('hidden'); startNew(true); } if(e.target.id==='discardInvalidBtn'){ localStorage.removeItem(STORAGE_KEY); startNew(true); } if(e.target.matches('.area-tab')){ state.activeArea=e.target.dataset.area; renderAreas(); renderItems(); } if(e.target.matches('.score-btn')){ const code=e.target.dataset.code; const v=e.target.dataset.score==='null'?null:Number(e.target.dataset.score); if(v===null) delete state.assessment.observedResponses[code]; else state.assessment.observedResponses[code]=v; document.querySelectorAll(`.score-btn[data-code="${code}"]`).forEach(b=>b.setAttribute('aria-pressed', String(b===e.target))); rescore(); }});
document.addEventListener('input',(e)=>{ if(['patientName','birthDate','assessmentDate','ageMonths'].includes(e.target.id)) onMeta(e); if(e.target.matches('textarea[data-obs]')){ state.assessment.observations[e.target.dataset.obs]=e.target.value; save(); }}); document.addEventListener('change',(e)=>{ if(e.target.id==='manualAgeOverride') onMeta(e); });
init();
