import test from 'node:test';
import assert from 'node:assert/strict';
import { buildPreviousScoreReference, copyObservedResponsesForSubarea, createFollowUpAssessmentSeed, restoreResponsesForSubarea } from '../src/battelle-follow-up.js';

const previous={id:'bat-previous',name:'Caso',therapistName:'Ana',birthDate:'2020-01-01',assessmentDate:'2025-01-01',observedResponses:{A1:2,A3:0,B1:1},observations:{'subarea:A':'privada'},workflowStatus:'corregida',revision:9,createdAt:'2025-01-01T00:00:00.000Z',updatedAt:'2025-02-01T00:00:00.000Z',correctionMetadata:{fingerprint:'old'}};
test('semilla crea un documento clínico independiente y vacío',()=>{const before=structuredClone(previous);const seed=createFollowUpAssessmentSeed({previousAssessment:previous,now:new Date('2026-07-30T10:00:00Z'),id:'bat-new'});assert.equal(seed.id,'bat-new');assert.equal(seed.referenceAssessmentId,'bat-previous');assert.equal(seed.revision,0);assert.deepEqual(seed.observedResponses,{});assert.deepEqual(seed.observations,{});assert.deepEqual(seed.correctionMetadata,{});assert.equal(seed.workflowStatus,'borrador');assert.equal(seed.assessmentDate,'2026-07-30');assert.deepEqual(previous,before);});
test('copia solo observadas válidas de la subárea y conserva las demás',()=>{const current={A1:0,A2:1,B2:2};const next=copyObservedResponsesForSubarea({currentResponses:current,previousObservedResponses:{A1:2,A2:{puntuacion:2,origen:'basal'},A3:0,A4:4,B1:1},itemCodes:['A1','A2','A3','A4']});assert.deepEqual(next,{B2:2,A1:2,A3:0});assert.deepEqual(current,{A1:0,A2:1,B2:2});});
test('deshacer recupera exactamente la subárea sin afectar otras respuestas',()=>{const restored=restoreResponsesForSubarea({currentResponses:{A1:2,A3:0,B2:2},previousCurrentResponses:{A1:0,A2:1},itemCodes:['A1','A2','A3']});assert.deepEqual(restored,{B2:2,A1:0,A2:1});});
test('referencia distingue observada, basal, techo y pendiente sin mutar',()=>{const items=['A1','A2','A3','A4'].map(c=>({codigo_canonico:c}));const before=structuredClone(previous);const ref=buildPreviousScoreReference({previousAssessment:previous,items,model:{x:1},scoreAssessment:()=>({respuestas_efectivas:{A1:{puntuacion:1,origen:'observado'},A2:{puntuacion:2,origen:'basal'},A3:{puntuacion:0,origen:'techo'}}})});assert.deepEqual(Object.values(ref.scores).map(x=>x.label),['1 OBS.','2 BASAL','0 TECHO','—']);assert.deepEqual(previous,before);});
test('impide autorreferencia',()=>assert.throws(()=>createFollowUpAssessmentSeed({previousAssessment:previous,id:previous.id}),/no es válida/));

import { createAssessmentRecord, getAssessment, listAssessments, saveAssessment } from '../src/battelle-assessment-repository.js';
function memoryStorage(){const data=new Map();return {getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};}
test('regresión multidispositivo conserva íntegra la anterior y guarda dos filas independientes',async()=>{const storage=memoryStorage();const old=createAssessmentRecord({...previous,observations:{},schemaVersion:3,ageMonths:60,manualAgeOverride:true,deletedAt:null,deletedBy:null,deletionRevision:null});const savedOld=await saveAssessment(old,storage,{now:()=>old.updatedAt,expectedRevision:0});const oldSnapshot=structuredClone(savedOld);const seed=createAssessmentRecord(createFollowUpAssessmentSeed({previousAssessment:savedOld,now:new Date('2026-07-30T10:00:00Z'),id:'bat-device-b'}));seed.observedResponses=copyObservedResponsesForSubarea({currentResponses:{},previousObservedResponses:savedOld.observedResponses,itemCodes:['A1','A2','A3']});const savedNew=await saveAssessment(seed,storage,{now:()=>seed.updatedAt,expectedRevision:0});assert.deepEqual(await getAssessment(savedOld.id,storage),oldSnapshot);assert.notEqual(savedNew.id,savedOld.id);assert.equal(savedNew.referenceAssessmentId,savedOld.id);assert.deepEqual((await listAssessments(storage)).map(x=>x.id).sort(),['bat-device-b','bat-previous']);});
