import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeHistoryNumber,assessmentsBelongToSamePatient,findCorrectedAssessmentsByHistoryNumber,createFollowUpAssessmentSeed} from '../src/battelle-history-number.js';
import {createAssessmentRecord,filterAssessments} from '../src/battelle-assessment-repository.js';

test('NH conserva ceros y signos y normaliza espacios y mayúsculas',()=>{assert.equal(normalizeHistoryNumber('002314'),'002314');assert.equal(normalizeHistoryNumber(' nh-002314 '),'NH-002314');assert.equal(normalizeHistoryNumber(' AB   /  0012 '),'AB / 0012');});
test('NH rechaza valores suministrados inválidos',()=>{for(const value of ['', '   ', 2314, {}, [], '<b>NH</b>', 'NH\n1', 'x'.repeat(51)])assert.throws(()=>normalizeHistoryNumber(value));assert.equal(normalizeHistoryNumber(null),null);});
test('documentos antiguos son compatibles como NH null',()=>{const record=createAssessmentRecord({birthDate:'',assessmentDate:'2026-01-01'});delete record.historyNumber;const clean=createAssessmentRecord(record);assert.equal(clean.historyNumber,null);});
test('identidad longitudinal depende exclusivamente de NH válido',()=>{assert.equal(assessmentsBelongToSamePatient({historyNumber:' nh-01',name:'A'},{historyNumber:'NH-01',name:'B'}),true);assert.equal(assessmentsBelongToSamePatient({historyNumber:'01',name:'A'},{historyNumber:'02',name:'A'}),false);assert.equal(assessmentsBelongToSamePatient({name:'A'},{name:'A'}),false);});
test('búsqueda local incluye NH, paciente y terapeuta sin acentos',()=>{const rows=[{historyNumber:'002314',name:'Ángela Pérez',therapistName:'María Sol',workflowStatus:'borrador'}];for(const query of ['002314','angela   perez','maria sol'])assert.equal(filterAssessments(rows,{query}).length,1);});
test('filtra corregidas del NH sin mutar y ordenadas por fecha',()=>{const rows=[{id:'self',historyNumber:'01',workflowStatus:'corregida',deletedAt:null,assessmentDate:'2025-02-01'},{id:'b',historyNumber:' 01 ',workflowStatus:'corregida',deletedAt:null,assessmentDate:'2025-03-01'},{id:'a',historyNumber:'01',workflowStatus:'corregida',deletedAt:null,assessmentDate:'2024-01-01'},{id:'draft',historyNumber:'01',workflowStatus:'borrador',deletedAt:null},{id:'trash',historyNumber:'01',workflowStatus:'corregida',deletedAt:'x'}];const before=structuredClone(rows);assert.deepEqual(findCorrectedAssessmentsByHistoryNumber(rows,'01','self').map(x=>x.id),['a','b']);assert.deepEqual(rows,before);});
test('semilla de nueva Battelle copia exclusivamente identificación permitida',()=>{const seed=createFollowUpAssessmentSeed({historyNumber:' nh-01 ',name:'M.P.',birthDate:'2020-01-01',therapistName:'Ana',id:'old',revision:9,observedResponses:{A:2},observations:{A:'x'},results:{x:1}},new Date(2026,6,29));assert.deepEqual(seed,{historyNumber:'NH-01',name:'M.P.',birthDate:'2020-01-01',therapistName:'Ana',assessmentDate:'2026-07-29'});const fresh=createAssessmentRecord(seed);assert.notEqual(fresh.id,'old');assert.deepEqual(fresh.observedResponses,{});assert.deepEqual(fresh.observations,{});assert.deepEqual(fresh.correctionMetadata,{});assert.equal(fresh.revision,0);});
