import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const files=async()=>{const [html,script,css]=await Promise.all(['index.html','script.js','styles.css'].map(path=>readFile(path,'utf8')));return {html,script,css};};

test('la carga correcta oculta el resumen técnico y los baremos inválidos conservan un error bloqueante',async()=>{const {html,script}=await files();assert.doesNotMatch(html,/Datos cargados: 341 ítems/);assert.doesNotMatch(script,/`Datos cargados:/);assert.match(script,/normativeValidation\.ok/);assert.match(script,/NORMATIVE_ERROR_MESSAGE/);assert.match(html,/aria-live="assertive"/);});
test('inicio comienza por Evaluaciones y ofrece una sola Nueva Battelle',async()=>{const {html}=await files();assert.doesNotMatch(html,/home-hero|Evaluación y corrección del Battelle|Evaluaciones guardadas/);assert.equal((html.match(/>Nueva Battelle</g)||[]).length,1);assert.match(html,/<h2 id="savedTitle">Evaluaciones<\/h2>/);});
test('tabla principal elimina Progreso, usa fechas españolas y edad compacta',async()=>{const {script}=await files();const home=script.slice(script.indexOf('async function renderHome('),script.indexOf('\nasync function removeAssessment'));assert.doesNotMatch(home,/['"]Progreso['"]/);assert.match(home,/\['Paciente','Nacimiento','Evaluación','Edad','Estado','Última modificación','Acciones'\]/);assert.match(script,/displayDate\(value\)/);assert.match(script,/\$\{match\[3\]\}\/\$\{match\[2\]\}\/\$\{match\[1\]\}/);assert.match(script,/function compactAge/);});
test('estados de administración distinguen resultado vigente, cambios y bloqueo',async()=>{const {script}=await files();for(const label of ['En administración','Resultado actualizado','Cambios pendientes de corregir','Revisión necesaria'])assert.match(script,new RegExp(label));assert.match(script,/corrected=state\.evaluationStatus==='corregida'.*!isCorrectionStale/);});
test('subáreas separan título, indicadores, instrucción y detalles cerrados',async()=>{const {script}=await files();for(const token of ['subarea-title','subarea-indicators','clinical-instruction','Detalles de administración'])assert.match(script,new RegExp(token));assert.match(script,/el\('details',\{class:'administration-details'\}/);assert.doesNotMatch(script,/class:'administration-details'.*open:/);});
test('ítems conservan origen textual, controles accesibles y atajos',async()=>{const {script,css}=await files();assert.match(script,/scorePresentation\(response\)/);assert.match(script,/ariaLabel:a\.ariaLabel/);assert.match(script,/scoreMap=\{0:'0',1:'1',2:'2'/);for(const origin of ['basal','techo','observado']) assert.match(css,new RegExp(`data-origin=${origin}`));});
test('resultados configurables, copia, detalles y PDF permanecen conectados',async()=>{const {script}=await files();for(const token of ['RESULT_FORMATS','createResultPresentation','copyResultTable','copyConclusionBtn','downloadBattellePdf','Detalles técnicos'])assert.match(script,new RegExp(token));assert.match(script,/el\('details',\{class:'technical-block'\}/);});
test('la presentación segura evita valores técnicos accidentales',async()=>{const {script}=await files();assert.match(script,/undefined\|null\|\\\[object Object\\\]/);assert.match(script,/function safeText/);});
test('el CSS centraliza semántica clínica, foco y movimiento reducido',async()=>{const {css}=await files();for(const token of ['--basal','--ceiling','--warning-bg','--error-bg','--radius','prefers-reduced-motion','focus-visible'])assert.match(css,new RegExp(token));});
