export const STORAGE_KEY = 'battelleAssessmentV2';
export const LEGACY_KEY = 'battellePrototype';
export const SCHEMA_VERSION = 2;
export function todayIso(date = new Date()) { return date.toISOString().slice(0,10); }
export function createAssessment(now = new Date()) { const iso = now.toISOString(); return { id: `bat-${iso.replace(/[-:.TZ]/g,'')}-${Math.random().toString(36).slice(2,8)}`, schemaVersion: SCHEMA_VERSION, name: '', birthDate: '', assessmentDate: todayIso(now), ageMonths: null, manualAgeOverride: false, observedResponses: {}, observations: {}, createdAt: iso, updatedAt: iso }; }
export function hasAssessmentChanges(a) { return Boolean(a && (a.name || a.birthDate || Object.keys(a.observedResponses||{}).length || Object.values(a.observations||{}).some(Boolean))); }
export function calculateAgeMonths(birthDate, assessmentDate) { if (!birthDate || !assessmentDate) return { ok:false, error:'faltan_fechas' }; const b=new Date(`${birthDate}T00:00:00Z`), e=new Date(`${assessmentDate}T00:00:00Z`); if (Number.isNaN(+b)||Number.isNaN(+e)) return { ok:false, error:'fecha_invalida' }; if (e < b) return { ok:false, error:'evaluacion_antes_nacimiento' }; let months=(e.getUTCFullYear()-b.getUTCFullYear())*12 + e.getUTCMonth()-b.getUTCMonth(); if (e.getUTCDate() < b.getUTCDate()) months--; if (months < 0) return { ok:false, error:'evaluacion_antes_nacimiento' }; if (months > 95) return { ok:false, error:'fuera_de_rango', months }; return { ok:true, months }; }
export function formatAge(months) { if (!Number.isInteger(months)) return 'Edad sin definir'; const y=Math.floor(months/12), m=months%12; return `${y} año${y===1?'':'s'} y ${m} mes${m===1?'':'es'} (${months} meses)`; }
export function serializeAssessment(a) { return JSON.stringify({ schemaVersion: SCHEMA_VERSION, assessment: { id:a.id, schemaVersion: SCHEMA_VERSION, name:a.name, birthDate:a.birthDate, assessmentDate:a.assessmentDate, ageMonths:a.ageMonths, manualAgeOverride:!!a.manualAgeOverride, observedResponses:a.observedResponses||{}, observations:a.observations||{}, createdAt:a.createdAt, updatedAt:a.updatedAt } }); }
export function parseStoredAssessment(text) { if (!text) return { ok:false, reason:'empty' }; try { const data=JSON.parse(text); const a=data.assessment; if (data.schemaVersion !== SCHEMA_VERSION || !a || a.schemaVersion !== SCHEMA_VERSION) return { ok:false, reason:'version_incompatible' }; return { ok:true, assessment:{...a, observedResponses:a.observedResponses||{}, observations:a.observations||{}} }; } catch { return { ok:false, reason:'json_corrupto' }; } }
export function loadStoredAssessment(storage) { return { current: parseStoredAssessment(storage.getItem(STORAGE_KEY)), legacyDetected: storage.getItem(LEGACY_KEY) !== null }; }
export function persistAssessment(storage, assessment) { storage.setItem(STORAGE_KEY, serializeAssessment({...assessment, updatedAt:new Date().toISOString()})); }
