import { displayValue, NOT_APPLICABLE } from './battelle-result-table.js';

export function safePdfFilename(name,date){ const safe=String(name||'Evaluacion').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'Evaluacion'; const d=/^\d{4}-\d{2}-\d{2}$/.test(date||'')?date:'sin-fecha'; return `Battelle_${safe}_${d}.pdf`; }
const latin=s=>String(s).replace(/[\u2013\u2014]/g,'-').replace(/\u20ac/g,'EUR').replace(/[^\x20-\x7e\xA0-\xFF]/g,'?').replace(/([\\()])/g,'\\$1');
function pdfDocument(pages){
  const objects=['<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>','']; const pageIds=[];
  for(const content of pages){const contentId=objects.length+1;objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);const pageId=objects.length+1;pageIds.push(pageId);objects.push(`<< /Type /Page /Parent 3 0 R /MediaBox [0 0 841.89 595.28] /Resources << /Font << /F1 1 0 R /F2 2 0 R >> >> /Contents ${contentId} 0 R >>`);}
  objects[2]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;const catalog=objects.length+1;objects.push('<< /Type /Catalog /Pages 3 0 R >>'); let out='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Uint8Array([...out].map(c=>c.charCodeAt(0)&255));
}
function text(x,y,value,size=8,bold=false){return `BT /F${bold?2:1} ${size} Tf ${x} ${y} Td (${latin(value)}) Tj ET`;}
function approxWidth(value,size){return String(value).length*size*.49;}
function fit(value,maxWidth,size=8){let output=String(value);while(output.length>1&&approxWidth(output,size)>maxWidth)output=output.slice(0,-1);return output.length<String(value).length?`${output.slice(0,-1)}…`:output;}
function wrap(value,maxWidth,size=8){
  const paragraphs=String(value).split(/\r?\n/), lines=[];
  for(const paragraph of paragraphs){const words=paragraph.split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue;}let line='';for(const word of words){const candidate=line?`${line} ${word}`:word;if(approxWidth(candidate,size)<=maxWidth)line=candidate;else{if(line)lines.push(line);if(approxWidth(word,size)<=maxWidth)line=word;else{let rest=word;while(approxWidth(rest,size)>maxWidth){let count=Math.max(1,Math.floor(maxWidth/(size*.49)));lines.push(rest.slice(0,count));rest=rest.slice(count);}line=rest;}}}if(line)lines.push(line);}
  return lines;
}
const PAGE={left:32,right:810,top:561,bottom:38,footer:22,row:19,tableHeader:22};
const widths=[326,48,48,48,48,48,48,164];
const xs=widths.reduce((all,w)=>[...all,all.at(-1)+w],[PAGE.left]);
function fillRect(x,y,w,h,gray){return `${gray} g ${x} ${y} ${w} ${h} re f 0 g`;}
function lineRect(x,y,w,h){return `0.82 G ${x} ${y} ${w} ${h} re S 0 G`;}
function minimumHeader(commands,pageNumber){commands.push(text(PAGE.left,PAGE.top,'Neurointegra',10,true),text(PAGE.left,PAGE.top-17,'Resumen de resultados Battelle',15,true),text(700,PAGE.top-13,`Página ${pageNumber}`,8));return PAGE.top-35;}
function metadata(commands,model,y){const m=model.metadata,d=m.display||{};const cells=[['Paciente',m.name||NOT_APPLICABLE],['Nacimiento',d.birthDate||m.birthDate||NOT_APPLICABLE],['Evaluación',d.assessmentDate||m.assessmentDate||NOT_APPLICABLE],['Edad cronológica',d.age||NOT_APPLICABLE],['Corrección',d.correctedAt||m.correctedAt||NOT_APPLICABLE],['Profesional',d.professional||m.professional||NOT_APPLICABLE]];const cellW=(PAGE.right-PAGE.left)/3;for(let i=0;i<cells.length;i++){const x=PAGE.left+(i%3)*cellW,cy=y-Math.floor(i/3)*29;commands.push(text(x,cy,cells[i][0],6.5,true),text(x,cy-11,fit(cells[i][1],cellW-10,7.5),7.5));}return y-65;}
function columnHeader(commands,y){commands.push(fillRect(PAGE.left,y-PAGE.tableHeader+5,PAGE.right-PAGE.left,PAGE.tableHeader,.93),lineRect(PAGE.left,y-PAGE.tableHeader+5,PAGE.right-PAGE.left,PAGE.tableHeader));['Área / subárea','PD','PC','z','T','CI','ECN','Edad equivalente'].forEach((v,i)=>commands.push(text(xs[i]+4,y-9,v,7.5,true)));return y-PAGE.tableHeader;}
function tableRow(commands,row,y){const bottom=y-PAGE.row+3;if(row.type!=='subarea')commands.push(fillRect(PAGE.left,bottom,PAGE.right-PAGE.left,PAGE.row,row.type==='grand-total'?.87:.94));commands.push(lineRect(PAGE.left,bottom,PAGE.right-PAGE.left,PAGE.row));const values=[row.label,row.pd,row.pc,row.z,row.T,row.CI,row.ECN,row.equivalentAge].map(displayValue);values.forEach((v,i)=>{const shown=fit(v,widths[i]-8,i?7.2:7.7);const x=i===0?xs[i]+4:xs[i]+(widths[i]-approxWidth(shown,7.2))/2;commands.push(text(x,y-10,shown,i?7.2:7.7,row.type!=='subarea'));});return y-PAGE.row;}
function footer(commands,page,total){commands.push(text(PAGE.left,PAGE.footer,'Resultados Battelle · interpretación a cargo del profesional responsable.',6.8),text(742,PAGE.footer,`Página ${page} de ${total}`,7,true));}
function warningBlocks(warnings){return warnings.flatMap(w=>{const prefix=`${w.item}: `;const lines=wrap(prefix+w.message,PAGE.right-PAGE.left-16,8);return [{lines,height:18+lines.length*11}];});}
export function generateBattellePdf(model){
  if(!model?.rows?.length)throw new TypeError('Modelo de resultados vacío.');
  const pageRows=[];let cursor=0;const firstCapacity=18,otherCapacity=21;while(cursor<model.rows.length){const capacity=pageRows.length?otherCapacity:firstCapacity;pageRows.push(model.rows.slice(cursor,cursor+capacity));cursor+=capacity;}
  const warningGroups=warningBlocks(model.warnings||[]);const pageSpecs=pageRows.map((rows,index)=>({rows,warnings:index===pageRows.length-1?warningGroups:[]}));
  if(warningGroups.length){const last=pageSpecs.at(-1);const used=(last.rows.length*PAGE.row)+PAGE.tableHeader+100;let room=PAGE.top-PAGE.bottom-used-25;const kept=[];for(const block of warningGroups){if(block.height<=room){kept.push(block);room-=block.height;}else break;}last.warnings=kept;const remaining=warningGroups.slice(kept.length);if(remaining.length)pageSpecs.push({rows:[],warnings:remaining});}
  const total=pageSpecs.length;const pages=pageSpecs.map((spec,index)=>{const commands=[];let y=minimumHeader(commands,index+1);if(index===0)y=metadata(commands,model,y);y=columnHeader(commands,y);for(const row of spec.rows)y=tableRow(commands,row,y);if(spec.warnings.length){y-=10;commands.push(text(PAGE.left,y,'Advertencias clínicas',10,true));y-=15;for(const block of spec.warnings){for(const warningLine of block.lines){commands.push(text(PAGE.left+8,y,warningLine,8));y-=11;}y-=7;}}footer(commands,index+1,total);return commands.join('\n');});return pdfDocument(pages);
}
export function downloadBattellePdf(model,env=globalThis){const bytes=generateBattellePdf(model);const filename=safePdfFilename(model.metadata.name,model.metadata.assessmentDate);const url=env.URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const a=env.document.createElement('a');a.href=url;a.download=filename;a.click();env.URL.revokeObjectURL(url);return {filename,bytes};}
