import { createResultPresentation, displayValue, NOT_APPLICABLE, selectResultColumns, RESULT_COLUMN_DEFINITIONS } from './battelle-result-table.js';

export function safePdfFilename(name,date){ const safe=String(name||'Evaluacion').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'Evaluacion'; const d=/^\d{4}-\d{2}-\d{2}$/.test(date||'')?date:'sin-fecha'; return `Battelle_${safe}_${d}.pdf`; }
const latin=s=>String(s).replace(/[\u2013\u2014]/g,'-').replace(/\u20ac/g,'EUR').replace(/[^\x20-\x7e\xA0-\xFF]/g,'?').replace(/([\\()])/g,'\\$1');
function pdfDocument(pages,orientation='landscape'){
  const objects=['<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>','']; const pageIds=[];
  const mediaBox=orientation==='portrait'?'595.28 841.89':'841.89 595.28';
  for(const content of pages){const contentId=objects.length+1;objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);const pageId=objects.length+1;pageIds.push(pageId);objects.push(`<< /Type /Page /Parent 3 0 R /MediaBox [0 0 ${mediaBox}] /Resources << /Font << /F1 1 0 R /F2 2 0 R >> >> /Contents ${contentId} 0 R >>`);}
  objects[2]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;const catalog=objects.length+1;objects.push('<< /Type /Catalog /Pages 3 0 R >>'); let out='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Uint8Array([...out].map(c=>c.charCodeAt(0)&255));
}
function text(x,y,value,size=8,bold=false){return `BT /F${bold?2:1} ${size} Tf ${x} ${y} Td (${latin(value)}) Tj ET`;}
function colorText(x,y,value,size=8,bold=false,color=[.09,.2,.18]){return `${color.join(' ')} rg ${text(x,y,value,size,bold)} 0 g`;}
function approxWidth(value,size){return String(value).length*size*.49;}
function fit(value,maxWidth,size=8){let output=String(value);while(output.length>1&&approxWidth(output,size)>maxWidth)output=output.slice(0,-1);return output.length<String(value).length?`${output.slice(0,-1)}…`:output;}
function wrap(value,maxWidth,size=8){
  const paragraphs=String(value).split(/\r?\n/), lines=[];
  for(const paragraph of paragraphs){const words=paragraph.split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue;}let line='';for(const word of words){const candidate=line?`${line} ${word}`:word;if(approxWidth(candidate,size)<=maxWidth)line=candidate;else{if(line)lines.push(line);if(approxWidth(word,size)<=maxWidth)line=word;else{let rest=word;while(approxWidth(rest,size)>maxWidth){let count=Math.max(1,Math.floor(maxWidth/(size*.49)));lines.push(rest.slice(0,count));rest=rest.slice(count);}line=rest;}}}if(line)lines.push(line);}
  return lines;
}
const PAGE={left:32,right:810,top:561,bottom:38,footer:22,row:19,tableHeader:22};
function pdfColumns(selection){
  const columns=selectResultColumns(selection); const available=PAGE.right-PAGE.left;
  const totalWeight=columns.reduce((sum,column)=>sum+column.recommendedWidth,0);
  const widths=columns.map(column=>available*column.recommendedWidth/totalWeight);
  const xs=widths.reduce((all,width)=>[...all,all.at(-1)+width],[PAGE.left]);
  return {columns,widths,xs};
}
function fillRect(x,y,w,h,gray){return `${gray} g ${x} ${y} ${w} ${h} re f 0 g`;}
function colorRect(x,y,w,h,color){return `${color.join(' ')} rg ${x} ${y} ${w} ${h} re f 0 g`;}
function lineRect(x,y,w,h,color=[.76,.81,.78]){return `${color.join(' ')} RG ${x} ${y} ${w} ${h} re S 0 G`;}
const PDF_COLORS={deep:[.05,.23,.21],teal:[.07,.43,.40],gold:[.74,.57,.31],ivory:[.97,.95,.90],sage:[.91,.95,.92],paper:[1,.99,.97],white:[1,1,1],muted:[.35,.43,.40]};
function minimumHeader(commands,pageNumber){commands.push(colorRect(0,PAGE.top-4,PAGE.right+32,42,PDF_COLORS.deep),colorRect(PAGE.left,PAGE.top-8,PAGE.right-PAGE.left,2,PDF_COLORS.gold),colorText(PAGE.left,PAGE.top+12,'NEUROINTEGRA',8,true,PDF_COLORS.gold),colorText(PAGE.left,PAGE.top-2,'Resumen de resultados Battelle',15,true,PDF_COLORS.white),colorText(PAGE.right-80,PAGE.top,`Página ${pageNumber}`,8,false,PDF_COLORS.white));return PAGE.top-38;}
function metadata(commands,model,y){const m=model.metadata,d=m.display||{};const cells=[['Paciente',m.name||NOT_APPLICABLE],['Nacimiento',d.birthDate||m.birthDate||NOT_APPLICABLE],['Evaluación',d.assessmentDate||m.assessmentDate||NOT_APPLICABLE],['Edad cronológica',d.age||NOT_APPLICABLE],['Corrección',d.correctedAt||m.correctedAt||NOT_APPLICABLE],['Terapeuta',d.therapistName||m.therapistName||'Sin asignar']];const cellW=(PAGE.right-PAGE.left)/3;commands.push(colorRect(PAGE.left-5,y-48,PAGE.right-PAGE.left+10,58,PDF_COLORS.ivory));for(let i=0;i<cells.length;i++){const x=PAGE.left+(i%3)*cellW,cy=y-Math.floor(i/3)*29;commands.push(colorText(x,cy,cells[i][0],6.5,true,PDF_COLORS.teal),colorText(x,cy-11,fit(cells[i][1],cellW-10,7.5),7.5,false,PDF_COLORS.deep));}return y-65;}
function columnHeader(commands,y,layout){commands.push(colorRect(PAGE.left,y-PAGE.tableHeader+5,PAGE.right-PAGE.left,PAGE.tableHeader,PDF_COLORS.teal));layout.columns.forEach((column,i)=>commands.push(colorText(layout.xs[i]+4,y-9,column.label,7.5,true,PDF_COLORS.white)));return y-PAGE.tableHeader;}
function tableRow(commands,row,y,layout){const bottom=y-PAGE.row+3;if(row.type==='total'||row.type==='grand-total')commands.push(colorRect(PAGE.left,bottom,PAGE.right-PAGE.left,PAGE.row,row.type==='grand-total'?PDF_COLORS.ivory:PDF_COLORS.sage));commands.push(lineRect(PAGE.left,bottom,PAGE.right-PAGE.left,PAGE.row));layout.columns.forEach((column,i)=>{const value=displayValue(row[column.value]),shown=fit(value,layout.widths[i]-8,i?7.2:7.7);const indent=row.type==='component'&&column.id==='label'?8:0;const x=column.alignment==='left'?layout.xs[i]+4+indent:layout.xs[i]+(layout.widths[i]-approxWidth(shown,7.2))/2;commands.push(colorText(x,y-10,shown,i?7.2:7.7,row.type==='total'||row.type==='grand-total',row.type==='grand-total'?PDF_COLORS.deep:[.12,.22,.2]));});return y-PAGE.row;}
function footer(commands,page,total){commands.push(`${PDF_COLORS.gold.join(' ')} RG ${PAGE.left} ${PAGE.footer+10} m ${PAGE.right} ${PAGE.footer+10} l S 0 G`,colorText(PAGE.left,PAGE.footer,'Resultados Battelle · interpretación a cargo del profesional responsable.',6.8,false,PDF_COLORS.muted),colorText(PAGE.right-68,PAGE.footer,`Página ${page} de ${total}`,7,true,PDF_COLORS.deep));}
function warningBlocks(warnings){return warnings.map(w=>{const lines=wrap(w.message,PAGE.right-PAGE.left-16,8);return {lines,height:18+lines.length*11};});}
export function generateBattellePdf(model,selection){
  if(!model?.rows?.length)throw new TypeError('Modelo de resultados vacío.');
  const presentation=model.format?model:createResultPresentation(model,{formatId:'complete',columns:selection??(Array.isArray(model.columns)&&typeof model.columns[0]==='object'?model.columns.map(column=>column.id):RESULT_COLUMN_DEFINITIONS.map(column=>column.id))});
  model=presentation;const orientation=presentation.orientation??(presentation.columns.length<=4?'portrait':'landscape');
  Object.assign(PAGE,orientation==='portrait'?{right:563,top:808}:{right:810,top:561});
  const normalizedSelection=presentation.columns.map(column=>column.id);
  const layout=pdfColumns(normalizedSelection); const pageRows=[];let cursor=0;const firstCapacity=orientation==='portrait'?30:18,otherCapacity=orientation==='portrait'?34:21;
  while(cursor<model.rows.length){const capacity=pageRows.length?otherCapacity:firstCapacity;pageRows.push(model.rows.slice(cursor,cursor+capacity));cursor+=capacity;}
  const warningGroups=warningBlocks(model.warnings||[]);const pageSpecs=pageRows.map((rows,index)=>({rows,warnings:index===pageRows.length-1?warningGroups:[],conclusion:null}));
  if(warningGroups.length){const last=pageSpecs.at(-1);const used=(last.rows.length*PAGE.row)+PAGE.tableHeader+100;let room=PAGE.top-PAGE.bottom-used-25;const kept=[];for(const block of warningGroups){if(block.height<=room){kept.push(block);room-=block.height;}else break;}last.warnings=kept;const remaining=warningGroups.slice(kept.length);if(remaining.length)pageSpecs.push({rows:[],warnings:remaining,conclusion:null});}
  if(model.conclusion?.ok){const lines=wrap(model.conclusion.text,PAGE.right-PAGE.left-16,8),height=42+lines.length*11;const last=pageSpecs.at(-1);const used=(last.rows.length*PAGE.row)+(last.rows.length?PAGE.tableHeader:0)+last.warnings.reduce((sum,w)=>sum+w.height,0)+80; if(PAGE.top-PAGE.bottom-used<height)pageSpecs.push({rows:[],warnings:[],conclusion:{lines,height}});else last.conclusion={lines,height};}
  const total=pageSpecs.length;const pages=pageSpecs.map((spec,index)=>{const commands=[];let y=minimumHeader(commands,index+1);if(index===0)y=metadata(commands,model,y);if(spec.rows.length){y=columnHeader(commands,y,layout);for(const row of spec.rows)y=tableRow(commands,row,y,layout);}if(spec.warnings.length){y-=10;commands.push(text(PAGE.left,y,'Puntuaciones para revisar',10,true));y-=15;for(const block of spec.warnings){for(const warningLine of block.lines){commands.push(text(PAGE.left+8,y,warningLine,8));y-=11;}y-=7;}}if(spec.conclusion){y-=12;commands.push(text(PAGE.left,y,'Conclusión descriptiva',10,true));y-=16;for(const conclusionLine of spec.conclusion.lines){commands.push(text(PAGE.left+8,y,conclusionLine,8));y-=11;}y-=5;commands.push(text(PAGE.left+8,y,model.conclusion.note,6.8));}footer(commands,index+1,total);return commands.join('\n');});return pdfDocument(pages,orientation);
}
export function downloadBattellePdf(model,selection,env=globalThis){const bytes=generateBattellePdf(model,selection);const filename=safePdfFilename(model.metadata.name,model.metadata.assessmentDate);const url=env.URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const a=env.document.createElement('a');a.href=url;a.download=filename;a.click();env.URL.revokeObjectURL(url);return {filename,bytes};}
